<?php

namespace ContainerZkrWen7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y6JER91.App\Entity\Formation' shared service.
     *
     * @return \App\Entity\Formation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Y6JER91": it references class "App\\Entity\\Formation" but no such service exists.');
    }
}
