<?php

namespace ContainerGRoEDRZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NB5r4rjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NB5r4rj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NB5r4rj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'playlists' => ['privates', '.errored..service_locator.NB5r4rj.App\\Entity\\Playlist', NULL, 'Cannot autowire service ".service_locator.NB5r4rj": it references class "App\\Entity\\Playlist" but no such service exists.'],
        ], [
            'playlists' => 'App\\Entity\\Playlist',
        ]);
    }
}
