<?php

namespace ContainerLObryz0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T4pH54gService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.t4pH54g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t4pH54g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flashBag' => ['privates', 'session.flash_bag', 'getSession_FlashBagService', true],
        ], [
            'flashBag' => '?',
        ]);
    }
}
