<?php

namespace ContainerLObryz0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCategoryControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminCategoryController' shared autowired service.
     *
     * @return \App\Controller\AdminCategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdminCategoryController.php';

        $container->services['App\\Controller\\AdminCategoryController'] = $instance = new \App\Controller\AdminCategoryController(($container->privates['App\\Repository\\PlaylistRepository'] ?? $container->load('getPlaylistRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\FormationRepository'] ?? $container->load('getFormationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\AdminCategoryController', $container));

        return $instance;
    }
}
