<?php

namespace ContainerLObryz0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpu_Oauth2_Client_KeycloakService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'knpu.oauth2.client.keycloak' shared service.
     *
     * @return \KnpU\OAuth2ClientBundle\Client\Provider\KeycloakClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/knpuniversity/oauth2-client-bundle/src/Client/Provider/KeycloakClient.php';

        return $container->services['knpu.oauth2.client.keycloak'] = new \KnpU\OAuth2ClientBundle\Client\Provider\KeycloakClient(($container->privates['knpu.oauth2.provider.keycloak'] ?? $container->load('getKnpu_Oauth2_Provider_KeycloakService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
