Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AccueilController",
            "name": "AccueilController",
            "summary": "Controleur\u0020de\u0020l\u0027accueil",
            "url": "classes/App-Controller-AccueilController.html"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Acgu\u0028\u0029",
            "name": "cgu",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method_cgu"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#property_repository"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController",
            "name": "AdminCategoryController",
            "summary": "Controleur\u0020des\u0020admins\u0020cat\u00E9gories",
            "url": "classes/App-Controller-AdminCategoryController.html"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003AaddCategory\u0028\u0029",
            "name": "addCategory",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#method_addCategory"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003AdeleteCategory\u0028\u0029",
            "name": "deleteCategory",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#method_deleteCategory"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminCategoryController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminCategoryController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController",
            "name": "AdminFormationsController",
            "summary": "Controleur\u0020des\u0020admins\u0020formations",
            "url": "classes/App-Controller-AdminFormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003AsearchByTitle\u0028\u0029",
            "name": "searchByTitle",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_searchByTitle"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003AsearchByPlaylist\u0028\u0029",
            "name": "searchByPlaylist",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_searchByPlaylist"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminFormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminFormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController",
            "name": "AdminPlaylistsController",
            "summary": "Controleur\u0020des\u0020admins\u0020playlists",
            "url": "classes/App-Controller-AdminPlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Trier\u0020une\u0020playlist",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_search"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\AdminPlaylistsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-AdminPlaylistsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\AuthenticateController",
            "name": "AuthenticateController",
            "summary": "Controleur\u0020des\u0020authentifications",
            "url": "classes/App-Controller-AuthenticateController.html"
        },                {
            "fqsen": "\\App\\Controller\\AuthenticateController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-AuthenticateController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController",
            "name": "FormationsController",
            "summary": "Controleur\u0020des\u0020formations",
            "url": "classes/App-Controller-FormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-FormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\OAuthController",
            "name": "OAuthController",
            "summary": "Controleur\u0020de\u0020l\u0027authentification",
            "url": "classes/App-Controller-OAuthController.html"
        },                {
            "fqsen": "\\App\\Controller\\OAuthController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-OAuthController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\OAuthController\u003A\u003AconnectCheckAction\u0028\u0029",
            "name": "connectCheckAction",
            "summary": "",
            "url": "classes/App-Controller-OAuthController.html#method_connectCheckAction"
        },                {
            "fqsen": "\\App\\Controller\\OAuthController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-OAuthController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController",
            "name": "PlaylistsController",
            "summary": "Controlleur\u0020des\u0020playlists",
            "url": "classes/App-Controller-PlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Entity\\Account",
            "name": "Account",
            "summary": "",
            "url": "classes/App-Entity-Account.html"
        },                {
            "fqsen": "\\App\\Entity\\Account\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Account.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Account\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Account.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Categorie",
            "name": "Categorie",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\Formation",
            "name": "Formation",
            "summary": "",
            "url": "classes/App-Entity-Formation.html"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAt\u0028\u0029",
            "name": "getPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPublishedAt\u0028\u0029",
            "name": "setPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAtString\u0028\u0029",
            "name": "getPublishedAtString",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAtString"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetMiniature\u0028\u0029",
            "name": "getMiniature",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getMiniature"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPicture\u0028\u0029",
            "name": "getPicture",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPicture"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetVideoId\u0028\u0029",
            "name": "getVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetVideoId\u0028\u0029",
            "name": "setVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPlaylist\u0028\u0029",
            "name": "getPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPlaylist\u0028\u0029",
            "name": "setPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetCategories\u0028\u0029",
            "name": "getCategories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getCategories"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AaddCategory\u0028\u0029",
            "name": "addCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_addCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AremoveCategory\u0028\u0029",
            "name": "removeCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_removeCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AcheminImage",
            "name": "cheminImage",
            "summary": "D\u00E9but\u0020de\u0020chemin\u0020vers\u0020les\u0020images",
            "url": "classes/App-Entity-Formation.html#constant_cheminImage"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024publishedAt",
            "name": "publishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_publishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024videoId",
            "name": "videoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_videoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024playlist",
            "name": "playlist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_playlist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024categories",
            "name": "categories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_categories"
        },                {
            "fqsen": "\\App\\Entity\\Playlist",
            "name": "Playlist",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetCategoriesPlaylist\u0028\u0029",
            "name": "getCategoriesPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getCategoriesPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "A\u0020visual\u0020identifier\u0020that\u0020represents\u0020this\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "Returning\u0020a\u0020salt\u0020is\u0020only\u0020needed,\u0020if\u0020you\u0020are\u0020not\u0020using\u0020a\u0020modern\nhashing\u0020algorithm\u0020\u0028e.g.\u0020bcrypt\u0020or\u0020sodium\u0029\u0020in\u0020your\u0020security.yaml.",
            "url": "classes/App-Entity-User.html#method_getSalt"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetKeycloakId\u0028\u0029",
            "name": "getKeycloakId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getKeycloakId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetKeycloakId\u0028\u0029",
            "name": "setKeycloakId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setKeycloakId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024keycloakId",
            "name": "keycloakId",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_keycloakId"
        },                {
            "fqsen": "\\App\\Form\\CategoryType",
            "name": "CategoryType",
            "summary": "",
            "url": "classes/App-Form-CategoryType.html"
        },                {
            "fqsen": "\\App\\Form\\CategoryType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-CategoryType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\CategoryType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-CategoryType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\FormationType",
            "name": "FormationType",
            "summary": "",
            "url": "classes/App-Form-FormationType.html"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-FormationType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-FormationType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType",
            "name": "PlaylistType",
            "summary": "",
            "url": "classes/App-Form-PlaylistType.html"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-PlaylistType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-PlaylistType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\AccountRepository",
            "name": "AccountRepository",
            "summary": "",
            "url": "classes/App-Repository-AccountRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\AccountRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-AccountRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\AccountRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Used\u0020to\u0020upgrade\u0020\u0028rehash\u0029\u0020the\u0020user\u0027s\u0020password\u0020automatically\u0020over\u0020time.",
            "url": "classes/App-Repository-AccountRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository",
            "name": "CategorieRepository",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllOrderBy\u0028\u0029",
            "name": "findAllOrderBy",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllOrderBy"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020des\u0020formations\u0020d\u0027une\u0020playlist",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllByName\u0028\u0029",
            "name": "findAllByName",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllByName"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindOneById\u0028\u0029",
            "name": "findOneById",
            "summary": "",
            "url": "classes/App-Repository-CategorieRepository.html#method_findOneById"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository",
            "name": "FormationRepository",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_findById"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllOrderBy\u0028\u0029",
            "name": "findAllOrderBy",
            "summary": "Retourne\u0020toutes\u0020les\u0020formations\u0020tri\u00E9es\u0020sur\u0020un\u0020champ",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllOrderBy"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide",
            "url": "classes/App-Repository-FormationRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllLasted\u0028\u0029",
            "name": "findAllLasted",
            "summary": "Retourne\u0020les\u0020n\u0020formations\u0020les\u0020plus\u0020r\u00E9centes",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllLasted"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020formations\u0020d\u0027une\u0020playlist",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllByTitle\u0028\u0029",
            "name": "findAllByTitle",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllByTitle"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllByPlaylistName\u0028\u0029",
            "name": "findAllByPlaylistName",
            "summary": "",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllByPlaylistName"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository",
            "name": "PlaylistRepository",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findById"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByName\u0028\u0029",
            "name": "findAllOrderByName",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020sur\u0020le\u0020nom\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByName"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByFormationsCount\u0028\u0029",
            "name": "findAllOrderByFormationsCount",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9s\u0020par\u0020nombre\u0020de\u0020formation",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByFormationsCount"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllByTitle\u0028\u0029",
            "name": "findAllByTitle",
            "summary": "",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllByTitle"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Used\u0020to\u0020upgrade\u0020\u0028rehash\u0029\u0020the\u0020user\u0027s\u0020password\u0020automatically\u0020over\u0020time.",
            "url": "classes/App-Repository-UserRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator",
            "name": "KeycloakAuthenticator",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method_start"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003AonAuthenticationFailure\u0028\u0029",
            "name": "onAuthenticationFailure",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method_onAuthenticationFailure"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003A\u0024clientRegistry",
            "name": "clientRegistry",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#property_clientRegistry"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\KeycloakAuthenticator\u003A\u003A\u0024router",
            "name": "router",
            "summary": "",
            "url": "classes/App-Security-KeycloakAuthenticator.html#property_router"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
