<?php

namespace ContainerJhhTSu6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CmX2rr8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cmX2rr8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cmX2rr8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminPlaylistsController::delete' => ['privates', '.service_locator.NB5r4rj', 'get_ServiceLocator_NB5r4rjService', true],
            'App\\Controller\\FormationsController::delete' => ['privates', '.service_locator.Y6JER91', 'get_ServiceLocator_Y6JER91Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminPlaylistsController:delete' => ['privates', '.service_locator.NB5r4rj', 'get_ServiceLocator_NB5r4rjService', true],
            'App\\Controller\\FormationsController:delete' => ['privates', '.service_locator.Y6JER91', 'get_ServiceLocator_Y6JER91Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminPlaylistsController::delete' => '?',
            'App\\Controller\\FormationsController::delete' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminPlaylistsController:delete' => '?',
            'App\\Controller\\FormationsController:delete' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
