<?php

namespace ContainerVTcyFR5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPlaylistsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminPlaylistsController' shared autowired service.
     *
     * @return \App\Controller\AdminPlaylistsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdminPlaylistsController.php';

        $container->services['App\\Controller\\AdminPlaylistsController'] = $instance = new \App\Controller\AdminPlaylistsController(($container->privates['App\\Repository\\PlaylistRepository'] ?? $container->load('getPlaylistRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\AdminPlaylistsController', $container));

        return $instance;
    }
}
