<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLObryz0\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLObryz0/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLObryz0.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLObryz0\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLObryz0\App_KernelTestDebugContainer([
    'container.build_hash' => 'LObryz0',
    'container.build_id' => 'c6506bbb',
    'container.build_time' => 1708227857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLObryz0');
