<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhhTSu6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhhTSu6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJhhTSu6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJhhTSu6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJhhTSu6\App_KernelDevDebugContainer([
    'container.build_hash' => 'JhhTSu6',
    'container.build_id' => '6ed6cc02',
    'container.build_time' => 1706567400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhhTSu6');
