<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGRoEDRZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGRoEDRZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGRoEDRZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGRoEDRZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGRoEDRZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'GRoEDRZ',
    'container.build_id' => '761955af',
    'container.build_time' => 1706396145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGRoEDRZ');
