<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVTcyFR5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVTcyFR5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVTcyFR5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVTcyFR5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVTcyFR5\App_KernelDevDebugContainer([
    'container.build_hash' => 'VTcyFR5',
    'container.build_id' => '6e18f1ed',
    'container.build_time' => 1706132873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVTcyFR5');
